/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package SistemaFerreteria.inventario;

import Sistema_Ferreteria.Datos.BaseDatos;
import Sistema_FerreteriaErick.pojos.Proveedor;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class ProveedorFrame extends javax.swing.JDialog {

    /**
     * Creates new form Proveedor
     */
    BaseDatos base = new BaseDatos();
    public ProveedorFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boxNameproveedor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        boxDirProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        boxDirNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        boxDirRegion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boxDirProvincia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        boxDirDistrito = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        boxTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        boxEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        boxNameContacto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Clave del Producto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jTextField1.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 26));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, 300, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Razon social/ Nombre del Proveedor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 12, -1, -1));

        boxNameproveedor.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        boxNameproveedor.setPreferredSize(new java.awt.Dimension(300, 26));
        jPanel1.add(boxNameproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 33, 340, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, 652, 15));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Direccion de Proveedor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, -1, -1));

        boxDirProveedor.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        boxDirProveedor.setPreferredSize(new java.awt.Dimension(500, 26));
        jPanel1.add(boxDirProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, 424, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 91, -1, -1));

        boxDirNumero.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        boxDirNumero.setPreferredSize(new java.awt.Dimension(56, 26));
        jPanel1.add(boxDirNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 118, 190, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Region:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 165, -1, -1));

        boxDirRegion.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        boxDirRegion.setPreferredSize(new java.awt.Dimension(186, 26));
        jPanel1.add(boxDirRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 186, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Provincia:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 165, -1, -1));

        boxDirProvincia.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        boxDirProvincia.setPreferredSize(new java.awt.Dimension(186, 26));
        jPanel1.add(boxDirProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 186, 186, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Distrito:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 165, -1, -1));

        boxDirDistrito.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        boxDirDistrito.setPreferredSize(new java.awt.Dimension(186, 26));
        jPanel1.add(boxDirDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 186, 190, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 223, 652, 10));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Telefono del Proveedor:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 241, -1, -1));

        boxTelefono.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        boxTelefono.setPreferredSize(new java.awt.Dimension(500, 26));
        jPanel1.add(boxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 239, 470, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Email del Proveedor:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 278, -1, -1));

        boxEmail.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        boxEmail.setPreferredSize(new java.awt.Dimension(500, 26));
        jPanel1.add(boxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 276, 470, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre de Contacto:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 315, -1, -1));

        boxNameContacto.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        boxNameContacto.setPreferredSize(new java.awt.Dimension(500, 26));
        jPanel1.add(boxNameContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 310, 470, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 370, -1, -1));

        jButton2.setText("Cancelar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre = boxNameproveedor.getText();
        String direccion = boxDirProveedor.getText();
        int numero = Integer.parseInt(boxDirNumero.getText());
        String region = boxDirRegion.getText();
        String provincia = boxDirProvincia.getText();
        String distrito = boxDirDistrito.getText();
        String telefono = boxTelefono.getText();
        String email = boxEmail.getText();
        String contacto = boxNameContacto.getText();
        Proveedor proveedor = new Proveedor(0, nombre, direccion, numero, region, provincia, distrito, telefono, email, contacto);
        
        base.insertarProveedor(proveedor);
        JOptionPane.showMessageDialog(this,"El proveedor se guardo correctamente");
        this.dispose();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProveedorFrame dialog = new ProveedorFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxDirDistrito;
    private javax.swing.JTextField boxDirNumero;
    private javax.swing.JTextField boxDirProveedor;
    private javax.swing.JTextField boxDirProvincia;
    private javax.swing.JTextField boxDirRegion;
    private javax.swing.JTextField boxEmail;
    private javax.swing.JTextField boxNameContacto;
    private javax.swing.JTextField boxNameproveedor;
    private javax.swing.JTextField boxTelefono;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
