/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package SistemaFerreteria.personal;

import Sistema_Ferreteria.Datos.BaseDatos;
import Sistema_FerreteriaErick.pojos.Acceso;
import Sistema_FerreteriaErick.pojos.Personal;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Date;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LAB07
 */
public class AltaPersonalFrame extends javax.swing.JDialog {

    /**
     * Creates new form AltaPersonalFrame
     */
    BaseDatos base = new BaseDatos();
    ArrayList<Personal> personal=new ArrayList<>();
    Integer personalSeleccionado;
    public AltaPersonalFrame(java.awt.Frame parent, boolean modal,Integer personalModificar) {
        super(parent, modal);
        initComponents();
        this.personalSeleccionado=personalModificar;
        if(personalModificar!=0){
        String dni=String.valueOf(personalModificar);
        personal=base.obtenerPersonalPorCriterio(dni);
        modificar();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoGrupo = new javax.swing.ButtonGroup();
        boximg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boxUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boxPass1 = new javax.swing.JPasswordField();
        boxPass2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        boxRol = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        boxNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        boxDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        boxDirFiscal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        boxSexoM = new javax.swing.JRadioButton();
        boxSexoF = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        boxDni = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        boxRuc = new javax.swing.JTextField();
        boxTelefono = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        boxCelular = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        boxFecNacimiento = new com.toedter.calendar.JDateChooser();
        boxFecInicio = new com.toedter.calendar.JDateChooser();
        boxFecFin = new com.toedter.calendar.JDateChooser();
        boxLugarNacimiento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boximg.setBackground(new java.awt.Color(153, 255, 102));
        boximg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personalDefault.png"))); // NOI18N
        boximg.setOpaque(true);
        boximg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boximgMousePressed(evt);
            }
        });
        getContentPane().add(boximg, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 12, 170, 173));

        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 57, 86, -1));
        getContentPane().add(boxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 147, 30));

        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 127, 86, -1));

        boxPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPass1ActionPerformed(evt);
            }
        });
        getContentPane().add(boxPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 154, 147, 30));
        getContentPane().add(boxPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 154, 147, 30));

        jLabel4.setText("Confirmar Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 127, 130, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 197, 711, 10));

        jLabel5.setText("Rol:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 213, -1, -1));

        boxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Trabajador", "Contador", "Gerencia" }));
        getContentPane().add(boxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 234, -1, -1));

        jLabel6.setText("Nombre del Personal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 213, -1, -1));
        getContentPane().add(boxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 237, 300, 30));

        jLabel7.setText("Direccion del Personal:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 276, -1, -1));
        getContentPane().add(boxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 303, 710, 30));

        jLabel11.setText("Domicilio Fiscal");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        boxDirFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDirFiscalActionPerformed(evt);
            }
        });
        getContentPane().add(boxDirFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 710, 30));

        jLabel12.setText("Lugar de Nacimiento:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 110, -1));

        jLabel13.setText("Sexo:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, -1, -1));

        sexoGrupo.add(boxSexoM);
        boxSexoM.setText("Masculino");
        getContentPane().add(boxSexoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, -1, -1));

        sexoGrupo.add(boxSexoF);
        boxSexoF.setText("Femenino");
        getContentPane().add(boxSexoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, -1));

        jLabel14.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 130, -1));

        jLabel16.setText("Fecha de Inicio de Contrato");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, -1));
        getContentPane().add(boxDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 160, 30));

        jLabel18.setText("DNI:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel19.setText("RUC:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));
        getContentPane().add(boxRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 160, 30));
        getContentPane().add(boxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, 150, 30));

        jLabel20.setText("Telefono fijo");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, -1, -1));

        jLabel21.setText("Celular:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, -1));
        getContentPane().add(boxCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 150, 30));

        jLabel22.setText("Fecha de fin de Contrato");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 150, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 190, 40));

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 190, 40));
        getContentPane().add(boxFecNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 150, 30));
        getContentPane().add(boxFecInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 30));
        getContentPane().add(boxFecFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 150, 30));
        getContentPane().add(boxLugarNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 430, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxDirFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDirFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDirFiscalActionPerformed
    private void modificar(){
        Personal per=personal.get(0);
        boxNombre.setText(per.getNombrePersonal());
        boxDireccion.setText(per.getDirPersonal());
        boxLugarNacimiento.setText(per.getLugarNacimientoPersonal());
        boxFecNacimiento.setDate(per.getFechaNacimientoPersonal());
        boxFecFin.setDate(per.getFechFincontrato());
        boxFecInicio.setDate(per.getFechInicioContrato());
        if("Masculino".equals(per.getSexoPersonal()))
            boxSexoM.setSelected(true);
        if("Femenino".equals(per.getSexoPersonal()))
            boxSexoF.setSelected(true);
        boxCelular.setText(per.getCelularPersonal().toString());
        boxDirFiscal.setText(per.getDomicilioFiscalPersonal());
        boxTelefono.setText(per.getTelefonoPerrsonal().toString());
        boxDni.setText(per.getDni().toString());
        boxRuc.setText(per.getRuc().toString());
        int rol=0;
        switch (per.getRolPersonal()){
            case "Administrador"->{
                rol=0;
            }
            case "Trabajador"->{
                rol=1;
            }
            case "Contador"->{
                rol=2;
            }
            case "Gerencia"->{
                rol=3;
            }
        }
        boxRol.setSelectedIndex(rol);
        try
        {
            BufferedImage bi = ImageIO.read(base.buscarFotoPersonal(personal.get(0).getDni().toString()));
        ImageIcon foto=new ImageIcon(bi);
        Image img = foto.getImage();
        Image newImg=img.getScaledInstance(boximg.getWidth(), boximg.getHeight(), java.awt.Image.SCALE_SMOOTH);
        
        ImageIcon newicon = new ImageIcon(newImg);
        boximg.setIcon(newicon);
        } catch (IOException e)
        {
            e.printStackTrace(System.err);
        }
        boxUsuario.setEditable(false);
        boxNombre.setEditable(false);
        boxFecFin.setEnabled(false);
        boxFecNacimiento.setEnabled(false);
        boxFecInicio.setEnabled(false);
        boxLugarNacimiento.setEditable(false);
        boxRuc.setEditable(false);
        boxDni.setEditable(false);
        boxRol.setEditable(false);
        boxSexoF.setEnabled(false);
        boxSexoM.setEnabled(false);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        calcularEdad();
        calcularTiempoLaborado();
        if(personalSeleccionado==0){
            String usuario = boxUsuario.getText();
        String pass1 = boxPass1.getText();
        String pass2 = boxPass2.getText();
        String rol = boxRol.getSelectedItem().toString();
        String nombre = boxNombre.getText();
        String direccion = boxDireccion.getText();
        String sexo="";
        if(boxSexoM.isSelected())
            sexo="Masculino";
        if(boxSexoF.isSelected())
            sexo="Femenino";
        String direccionFiscal = boxDirFiscal.getText();
        String lugarNacimiento = boxLugarNacimiento.getText();
        Date fecNacimiento = new java.sql.Date(boxFecNacimiento.getDate().getTime());
        Date fecInicio = new java.sql.Date(boxFecInicio.getDate().getTime());
        Date fecFin = new java.sql.Date(boxFecFin.getDate().getTime());
        Integer dni = Integer.valueOf(boxDni.getText());
        Integer ruc = Integer.valueOf(boxRuc.getText());
        Integer celular = Integer.valueOf(boxCelular.getText());
        Integer telefono = Integer.valueOf(boxTelefono.getText());
        Personal personal = new Personal(imgArticleFile,rol,nombre,direccion,direccionFiscal,lugarNacimiento,sexo,fecNacimiento,calcularEdad(),fecInicio,fecFin,calcularTiempoLaborado(),dni,ruc,celular,telefono);
       Acceso acceso = new Acceso(usuario,pass1,String.valueOf(dni));
        base.insertarPersonal(personal, acceso);
        base.insertarAcceso(acceso);
        JOptionPane.showMessageDialog(null, "Personal registrado");
        this.dispose();
        return;
        }
        if(imgArticleFile!=null){
            String dni = boxDni.getText();
        String pass1 = boxPass1.getText();
        String pass2 = boxPass2.getText();
        String direccion = boxDireccion.getText();
        String direccionFiscal = boxDirFiscal.getText();
        Integer celular = Integer.valueOf(boxCelular.getText());
        Integer telefono = Integer.valueOf(boxTelefono.getText());
        Personal personal =new Personal(imgArticleFile,null,null,direccion,direccionFiscal,null,null,null,0,null,null,0,null,null,celular,telefono);
        try
        {
            base.actualizarPersonal(personal, pass1,direccion,direccionFiscal,celular,telefono,dni,true);
            this.dispose();
        } catch (FileNotFoundException ex)
        {
            Logger.getLogger(AltaPersonalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(pass1!=null){
            if(pass1==pass2){
                base.actualizarAcceso(dni, pass1);
            }else{
                JOptionPane.showMessageDialog(null, "Las contraseñas son diferentes");
            }
        }
        }else{
            String dni = boxDni.getText();
        String pass1 = boxPass1.getText();
        String pass2 = boxPass2.getText();
        String direccion = boxDireccion.getText();
        String direccionFiscal = boxDirFiscal.getText();
        Integer celular = Integer.valueOf(boxCelular.getText());
        Integer telefono = Integer.valueOf(boxTelefono.getText());
        Personal personal =new Personal(null,null,null,direccion,direccionFiscal,null,null,null,0,null,null,0,null,null,celular,telefono);
            try
            {
                base.actualizarPersonal(personal, pass1,direccion,direccionFiscal,celular,telefono,dni,false);
                this.dispose();
            } catch (FileNotFoundException ex)
            {
                Logger.getLogger(AltaPersonalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
       if(pass1!=null){
            if(pass1==pass2){
                base.actualizarAcceso(dni, pass1);
            }else{
                JOptionPane.showMessageDialog(null, "Las contraseñas son diferentes");
            }
        }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
   public int calcularEdad(){
       int edadActual;
        java.util.Date fechan=boxFecNacimiento.getDate();
        LocalDate date = fechan.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Period edad=Period.between(date, LocalDate.now());
        System.out.println(String.format("%d anios",edad.getYears()));
        edadActual=edad.getYears();
        return edadActual;
   }
   public int calcularTiempoLaborado(){
       int tiempoLaborado;
       java.util.Date fecInicio=boxFecInicio.getDate();
       LocalDate date= fecInicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       Period tiempo = Period.between(date, LocalDate.now());
       System.out.println(String.format("%d meses",tiempo.getMonths()));
       int añosamese=tiempo.getYears();
       int meses=tiempo.getMonths();
       tiempoLaborado=añosamese*12+meses;
       System.out.println("Tiempo laborado asdas "+tiempoLaborado);
       return tiempoLaborado;
   }
    File imgArticleFile=new File("E:\\taller8\\Ferreteria\\src\\img\\personalDefault.png");
    
    private void boximgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boximgMousePressed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de imagen Jpg, Jpge, gif o png","Jpge","png","gif","JPG","jpg");
        chooser.setFileFilter(filter);
        
        int returnval = chooser.showOpenDialog(this);
        if(returnval == JFileChooser.APPROVE_OPTION){
            int anchoImagen = boximg.getWidth();
            int altoImagen = boximg.getHeight();
            
            imgArticleFile = chooser.getSelectedFile();
            ImageIcon icono = new ImageIcon(imgArticleFile.getAbsolutePath());
            Image imagen = icono.getImage();
            Image imagenRedimensionada = imagen.getScaledInstance(anchoImagen,altoImagen, Image.SCALE_DEFAULT);
            
            ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);
            boximg.setIcon(iconoRedimensionado);
        }
    }//GEN-LAST:event_boximgMousePressed

    private void boxPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaPersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaPersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaPersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaPersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                AltaPersonalFrame dialog = new AltaPersonalFrame(new javax.swing.JFrame(), true,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxCelular;
    private javax.swing.JTextField boxDirFiscal;
    private javax.swing.JTextField boxDireccion;
    private javax.swing.JTextField boxDni;
    private com.toedter.calendar.JDateChooser boxFecFin;
    private com.toedter.calendar.JDateChooser boxFecInicio;
    private com.toedter.calendar.JDateChooser boxFecNacimiento;
    private javax.swing.JTextField boxLugarNacimiento;
    private javax.swing.JTextField boxNombre;
    private javax.swing.JPasswordField boxPass1;
    private javax.swing.JPasswordField boxPass2;
    private javax.swing.JComboBox<String> boxRol;
    private javax.swing.JTextField boxRuc;
    private javax.swing.JRadioButton boxSexoF;
    private javax.swing.JRadioButton boxSexoM;
    private javax.swing.JTextField boxTelefono;
    private javax.swing.JTextField boxUsuario;
    private javax.swing.JLabel boximg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup sexoGrupo;
    // End of variables declaration//GEN-END:variables
}
