/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package SistemaFerreteria.personal;

import Sistema_Ferreteria.Datos.BaseDatos;
import Sistema_FerreteriaErick.pojos.Pariente;

/**
 *
 * @author lucas
 */
public class ContactoPersonalFrame extends javax.swing.JDialog {

    /**
     * Creates new form ContactoPersonalFrame
     */
    BaseDatos base = new BaseDatos();
    public ContactoPersonalFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        boxParentesco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boxApellidos = new javax.swing.JTextField();
        boxCelular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        boxDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boxDniPersonal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boxNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 245, 89, 10));

        jLabel2.setText("Tipo de Parentezco:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 104, 102, -1));
        getContentPane().add(boxParentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 125, 102, 28));

        jLabel3.setText("Apellidos :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 171, -1, -1));
        getContentPane().add(boxApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 192, 246, 25));
        getContentPane().add(boxCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 125, 100, 28));

        jLabel4.setText("Celular:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 104, -1, -1));

        boxDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(boxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 244, 459, 29));

        jLabel5.setText("Dirección del pariente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 223, -1, -1));

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 322, 187, -1));

        jButton4.setText("Cancelar");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 322, 175, -1));

        jLabel1.setText("DNI del personal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));
        getContentPane().add(boxDniPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, 102, -1));

        jLabel6.setText("Nombres:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));
        getContentPane().add(boxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 246, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDireccionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Integer dniPersonal = Integer.valueOf(boxDniPersonal.getText());
        String parentesco = boxParentesco.getText();
        String apellido = boxApellidos.getText();
        String nombre = boxNombre.getText();
        String direccion = boxDireccion.getText();
        Integer celular = Integer.valueOf(boxCelular.getText());
        Pariente pariente = new Pariente(dniPersonal, parentesco,apellido,nombre,direccion,celular );
        base.insertarParientePersonal(pariente);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ContactoPersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ContactoPersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ContactoPersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ContactoPersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContactoPersonalFrame dialog = new ContactoPersonalFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxApellidos;
    private javax.swing.JTextField boxCelular;
    private javax.swing.JTextField boxDireccion;
    private javax.swing.JTextField boxDniPersonal;
    private javax.swing.JTextField boxNombre;
    private javax.swing.JTextField boxParentesco;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
